apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: applicationservice
  namespace: demo
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: m5-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: applicationservice
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: applicationservice-
      labels:
        build.appstudio.openshift.io/application: m5-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: applicationservice
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: demo
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio/application-service
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:demo-applicationservice-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:latest
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: applicationservice/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
